config/routes.rb
Rails.application.routes.draw do
  get 'admins/scaffold'
  resources :player_signups, only: [:delete]
  resources :listings
  resources :users
  resources :activities
  resources :venues
  resources :areas, only: [:index, :show] 
  namespace :admin do
    resources :users, only: [:delete]
    resources :venues, only: [:delete]
    resources :activities
    resources :areas, only: [:new, :create, :edit]
    resources :listings
  end

  post 'listings/:id', to: 'listings#join', as: 'join_listing'
  post 'player_signups/:id', to: 'listings#remove_player', as: 'delete_player_signup'


  # param: :slug
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  root 'welcome#home'

  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_user_password'
  patch '/users/:id', to: 'users#edit_password'

   # admin paths
  get '/admin', to: 'admins#index', as: 'admin'
  get '/admin/unauthorised_activities', to: 'admins#unauthorised_activities', as: 'unauthorised_activities'
  get '/activities/new', to: 'admins#new_activity'
  get '/admin/unauthorised_activities/:id/edit', to: 'admins#authorise', as: 'authorise_activity'
  
  patch '/admin/unauthorised_activities/:id', to: 'admins#update', as: 'update_activity'
  delete '/admin/unauthorised_activities/:id', to: 'admins#destroy_unauthorised_activity'

  # get '/activities/:slug', to: 'activities#show', as: 'activity'
  # get '/activities/:slug/edit', to: 'activities#edit', as: 'edit_activity'
  # patch 'activities/:slug', to: 'activities#update'

  # get '/users/:slug', to: 'users#show', as: 'user'
  # get '/users/:slug/edit', to: 'users#edit', as: 'edit_user'
  # patch '/users/:slug', to: 'users#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/listing.rb
class Listing < ApplicationRecord
    has_many :player_signups, dependent: :destroy
    has_many :players, through: :player_signups
    belongs_to :venue
    belongs_to :activity
    belongs_to :organiser, class_name: "User"

    after_create :update_search_tags
    before_update :assign_search_tags

    validates :title, :venue_id, :activity_id, :organiser_id, presence: true
    validates :description, {
        presence: true,
        length: {minimum: 30}
    }
    validates :num_players, {
        presence: true,
        numericality: { 
            greater_than: 1,
            less_than: 21 
        }
    }

    def self.search(query)
      if query
        where('TAGS like ?', "%#{query}%")        
      else
        self.all
      end
    end

    def create_search_tags
      search_tags = []
      org = User.find(self.organiser_id)
      act = Activity.find(self.activity_id)
      ven = Venue.find(self.venue_id)
      area = Area.find(ven.area_id)
      search_tags << org.name
      search_tags << act.name
      search_tags << act.description
      search_tags << ven.name
      search_tags << area.name
      search_tags.join(" ")
    end

    def assign_search_tags
      self.tags = create_search_tags
    end

    def update_search_tags
      update_attributes tags: assign_search_tags
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :require_logged_in
  before_action :set_listing, only: [:show, :edit, :update, :destroy]


  # GET /listings
  # GET /listings.json
  def index
    if !params[:activity_id].blank?
      @listings = Listing.all.where(activity_id: params[:activity_id]).sort_by(&:date)
    else
      @listings = Listing.all.search(params[:query]).sort_by(&:date)
    end
  end

  def remove_player
    listing = Listing.find(params[:listing_id])
    signup = PlayerSignup.find_by(listing_id: listing.id, player_id: @user.id)
    signup.destroy
    flash[:notice] = "You're no longer attending this event. We've let the organiser know and removed it from your events"
    redirect_to listing_path(listing)
  end

  def join
    listing = Listing.find(params[:id])
    if listing.players.include? @user
      redirect_to listing_path(listing)
      flash[:notice] = "You're already signed up to this event!"
    elsif listing.organiser_id == @user.id
      redirect_to listing_path(listing)
      flash[:notice] = "You can't sign up to your own event!"
    else
      listing.players << @user
      activity = Activity.find(listing.activity_id)
      redirect_to listing_path(listing)
      flash[:notice] = "You're all signed up for #{activity.name}! It's been added to your profile."
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @activity = Activity.find(@listing.activity_id)
    @venue = Venue.find(@listing.venue_id)
    @organiser = User.find(@listing.organiser_id)
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
    unless @user.id == @listing.organiser_id
      redirect_to listing_path(@listing)
      flash[:notice] = "Sorry, you cannot edit someone elses listing."
    end
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.organiser_id = @user.id
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :venue_id, :activity_id, :organiser_id, :num_players, :description, :date)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date, required: true %>
  </div>

  <div class="field">
    <%= form.label :venue_id %>
    <%= form.collection_select(:venue_id, Venue.all.sort_by(&:form_name), :id, :form_name) %>
  </div>

  <div class="field">
    <%= form.label :activity_id %>
    <%= form.collection_select(:activity_id, Activity.all.where(authorised: true), :id, :name) %>
  </div>

  <div class="field">
    <%= form.label 'Number of players needed (Max 20)' %>
    <%= form.number_field :num_players %>
  </div>

  <div class="field">
    <%= form.label 'Description (Min 30 characters)' %>
    <%= form.text_area :description, size: "50x10" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<div class="listing-show">
  <div class="listing-heading-container">
    <div>
      <div>
        <div>
          <div class="listing-heading">
            <h1>Listings</h1><br>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="listing-search-container">
    <div>
      <div>
        <div>
          <div class="listing-search">
          <%= form_tag listings_path, :method => 'get' do %>
            <p>
              <%= text_field_tag :query, nil, :placeholder => "Search Listings" %>
              <%= submit_tag "Search", :name => nil %>
            </p>
          <% end %>
          <br>
          </div>
        </div>
      <div>
    </div>
  </div>
  <div class="reset-search-container">
    <div>
      <div>
        <div>
          <div class="reset-search">
            <h2><a href="/listings">Reset search</a></h2>
          </div>
        </div>
      <div>
    </div>
  </div>
</div>
</div>
  <br>
  <div>
    <div>
      <div>
        <div class="listings-index-container">
          <%= link_to new_listing_path, action: 'go' do %>
            <div class="new-listing-card">
              <div class="new-listing-card-image">
                <img src="https://icon-library.net/images/plus-icon-transparent/plus-icon-transparent-5.jpg" alt="add new activity">
              </div>
              <br><br>
              <h2>New Listing</h2>
            </div>      
          <% end %>
          <% @listings.each do |listing| %>
            <%= link_to listing_path(listing), action: 'go' do %>
              <% if listing.players.include? @user %>
              <div class="listing-card-attending">  
              <% elsif listing.organiser_id == @user.id %>
              <div class="listing-card-organiser">
              <% else %>
              <div class="listing-card">
              <% end %>
                <div class="listing-card-image">
                  <% activity = Activity.find_by(id: listing.activity_id) %> 
                  <img src=<%= activity.image_url %> alt=<%activity.name%>>
                </div>
                <br>
                <h3><%= listing.title %></h3>
                <p><%= listing.date.strftime("%a, %d %b") %></p>
                <br>
                <h4><%= activity.name %></h4>
                <br>
                <% ven = Venue.find_by(id: listing.venue_id) %>
                <p><%= ven.form_name %></p>
                <% if listing.num_players - listing.players.length <= 0 %>
                <br>
                <p><strong style="color:#f07727">All spots filled</strong></p> 
                <% else %>
                <p>Spaces remaining: <%= listing.num_players - listing.players.length %></p>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div> 
</div> 
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="notice"><p id="notice"><%= notice %></p></div>
<br>
<div class="listing-show">
  <div class="listing-head">
    <div class="listing-rosette">
    <% if @listing.players.include? @user %>
      <img src="https://i.imgur.com/AMVZZbd.jpg" alt="rosette">
      <% end %>
    </div>
    <div class="listing-title">
      <h1><%= @listing.title %></h1><br><br>
      <% if @listing.num_players - @listing.players.length > 0 %>
        <h2><%= @listing.num_players - @listing.players.length %> spots remaining.</h2><br>
      <% else %>
        <h2 style="color:#f07727">All the spots are filled for this event.</h2><br>
      <% end %>
      <% if @listing.players.include? @user %>
      <%= button_to "I can't make it", delete_player_signup_path, :method => :post, :params => { listing_id: @listing.id } %>
       <% elsif @listing.num_players - @listing.players.length > 0 %>
      <%= button_to "I'm in!", join_listing_path, :method => :post, :params => { listing_id: @listing.id } %>
        <% else %>
      <% end %>
      <br>
    </div>
  </div>

  <div class="listing">
    <div class="listing-activity-image-container">
      <div class="listing-activity-image">
        <img src="<%= @activity.image_url %>" alt="#{<%= @activity.name %>} image">
      </div>
    </div>
    <div class="listing-details">
      <div class="listing-date">
        <h3><%= @listing.date.strftime("%a, %d %b") %></h3>
      </div>
      <div class="listing-description">
        <strong>Description:</strong><br>
        <%= @listing.description %>
      </div>
    </div>

    <div class="listing-details-card">
      <div class="listing-specifics">
        <div class="listing-item">
          <strong>Venue:</strong>
          <%= @venue.name %> <br>
        </div>
        <div class="listing-item">
          <strong>Activity:</strong>
          <%= @activity.name %> <br>
        </div>
          <div class="listing-item">
          <strong>Organiser:</strong>
          <%= @organiser.name %> <br>
        </div>
          <div class="listing-item">
          <strong>Contact email:</strong>
          <%= @organiser.email %> <br>
        </div>
        <div class="listing-item">
          <strong>Number of players required:</strong>
          <%= @listing.num_players %> <br><br>
        </div>
        <div class="listing-item">
        <% if @listing.num_players - @listing.players.length < 0 %>
          <p><strong style="color:#f07727">All spots filled</strong></p>
        <% else %>
          <strong>Number of players attending:</strong>
          <%= @listing.players.length %>
        <% end %>
        </div>
      </div>
    </div>
  </div>

  <% if @user.id == @listing.organiser_id %>
    <%= link_to 'Edit Listing', edit_listing_path(@listing) %> |
    <%= link_to 'Delete Listing', @listing, method: :delete, data: { confirm: 'Are you sure?' } %> |
  <% end %>
  <%= link_to 'Back', listings_path %>
</div>