config/routes.rb
Rails.application.routes.draw do
  get 'admins/scaffold'
  resources :player_signups, only: [:delete]
  resources :listings
  resources :users
  resources :activities
  resources :venues
  resources :areas, only: [:index, :show] 
  namespace :admin do
    resources :users, only: [:delete]
    resources :venues, only: [:delete]
    resources :activities
    resources :areas, only: [:new, :create, :edit]
    resources :listings
  end

  post 'listings/:id', to: 'listings#join', as: 'join_listing'
  post 'player_signups/:id', to: 'listings#remove_player', as: 'delete_player_signup'


  # param: :slug
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  root 'welcome#home'

  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_user_password'
  patch '/users/:id', to: 'users#edit_password'

   # admin paths
  get '/admin', to: 'admins#index', as: 'admin'
  get '/admin/unauthorised_activities', to: 'admins#unauthorised_activities', as: 'unauthorised_activities'
  get '/activities/new', to: 'admins#new_activity'
  get '/admin/unauthorised_activities/:id/edit', to: 'admins#authorise', as: 'authorise_activity'
  
  patch '/admin/unauthorised_activities/:id', to: 'admins#update', as: 'update_activity'
  delete '/admin/unauthorised_activities/:id', to: 'admins#destroy_unauthorised_activity'

  # get '/activities/:slug', to: 'activities#show', as: 'activity'
  # get '/activities/:slug/edit', to: 'activities#edit', as: 'edit_activity'
  # patch 'activities/:slug', to: 'activities#update'

  # get '/users/:slug', to: 'users#show', as: 'user'
  # get '/users/:slug/edit', to: 'users#edit', as: 'edit_user'
  # patch '/users/:slug', to: 'users#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/admins/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, required: true %>
  </div>

  <div class="field">
    <%= form.label 'Description: (please be as detailed as you can)' %>
    <%= form.text_area :description, size: "50x10", required: true %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :wiki_link %>
    <%= form.text_field :wiki_link, required: true%>
  </div>

  <div class="field">
    <%= form.label :authorised %>
    <%= form.text_field :authorised, required: true%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/authorise.html.erb
<h1>You are currently trying to authorise <%= @activity.name%> and add it to the database.</h2>
<%= form_for @activity do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, required: true %>

    <%= f.label 'Description: (please be as detailed as you can)' %>
    <%= f.text_area :description, size: "50x10", required: true %>

    <%= f.label :image_url %>
    <%= f.text_field :image_url %>

    <%= f.label :wiki_link %>
    <%= f.text_field :wiki_link, required: true%>

    <%= f.label :authorised %>
    <%= f.check_box :authorised, required: true%>

  <%= f.submit, :params => = {activity_slug: @activity.slug} %>
<% end %>
<%= button_to "Delete #{@activity.name} and remove from database", update_activity_path(@activity.id), method: :delete, data:{confirm: "Are you sure you want to permenantly remove #{@activity.name} from the database?"} %>

app/views/admins/index.html.erb
<h1>Admins page</h1>

<p><%= User.all.count%>, <%= link_to 'Users', users_path %></p>
<p><%= Activity.all.count%>, <%= link_to 'Activities', activities_path %></p>
<p><%= Listing.all.count%>, <%= link_to 'Listings', listings_path %></p>
<p><%= @not_activities.count%>, <%= link_to 'Activities needing to be accepted', unauthorised_activities_path %></p>
<p><%= Area.all.count%>, <%= link_to 'Areas', areas_path %></p>

<p><%= link_to 'Create new activity', new_activity_path %></p>
<p>All users</p>
<p>All users</p>

app/views/admins/unauthorised_activities.html.erb
<h1>The following activities need to be authorised by an admin</h1>
<br>
<% @not_activities.each do |activity| %>
<p>This activity <%= link_to activity.name, activity_path(activity.slug) %> is currently authorised as <%= activity.authorised %></p>
<p>Would you like to <%= link_to "authorise?", "/admin/unauthorised_activities/#{activity.slug}/edit" %></p>
<br>
<% end %>