config/routes.rb
Rails.application.routes.draw do
  get 'admins/scaffold'
  resources :player_signups, only: [:delete]
  resources :listings
  resources :users
  resources :activities
  resources :venues
  resources :areas, only: [:index, :show] 
  namespace :admin do
    resources :users, only: [:delete]
    resources :venues, only: [:delete]
    resources :activities
    resources :areas, only: [:new, :create, :edit]
    resources :listings
  end

  post 'listings/:id', to: 'listings#join', as: 'join_listing'
  post 'player_signups/:id', to: 'listings#remove_player', as: 'delete_player_signup'


  # param: :slug
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  root 'welcome#home'

  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_user_password'
  patch '/users/:id', to: 'users#edit_password'

   # admin paths
  get '/admin', to: 'admins#index', as: 'admin'
  get '/admin/unauthorised_activities', to: 'admins#unauthorised_activities', as: 'unauthorised_activities'
  get '/activities/new', to: 'admins#new_activity'
  get '/admin/unauthorised_activities/:id/edit', to: 'admins#authorise', as: 'authorise_activity'
  
  patch '/admin/unauthorised_activities/:id', to: 'admins#update', as: 'update_activity'
  delete '/admin/unauthorised_activities/:id', to: 'admins#destroy_unauthorised_activity'

  # get '/activities/:slug', to: 'activities#show', as: 'activity'
  # get '/activities/:slug/edit', to: 'activities#edit', as: 'edit_activity'
  # patch 'activities/:slug', to: 'activities#update'

  # get '/users/:slug', to: 'users#show', as: 'user'
  # get '/users/:slug/edit', to: 'users#edit', as: 'edit_user'
  # patch '/users/:slug', to: 'users#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :player_signups, foreign_key: "player_id"
    has_many :listings, through: :player_signups

    has_many :listings, foreign_key: "organiser_id", dependent: :destroy
    has_many :activities, through: :listings
    has_many :player_signups, through: :listings

    validates :name, {
        presence: true,
        uniqueness: true,
        length: { in: 2..30},
        format: { with: /\A([a-zA-Z]+[ \-']?)+[a-zA-Z]+\z/,
            message: "Name must be a real name, it only allows letters and a space between names" }
    }
    

    validates :age, {
        presence: true,
        numericality: { 
            only_integer: true,
            greater_than: 16, 
            less_than: 60
        }
    }

    validates :bio, {
        presence: true,
        length: { minimum: 20}
    }

    validates :email, {
        presence: true,
        on: :create,
        uniqueness: true,
        format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }
    }

    def events_attended
        PlayerSignup.all.where(player_id: self.id)
    end

    def events_organised
        Listing.all.where(organiser_id: self.id)
    end

    def listings_attending
        listings = []
        self.events_attended.each do |signup|
            listing = Listing.find(signup.listing_id)
            listings << listing
        end
        listings.uniq
    end

    def activities
        activities = []
        self.events_organised.each do |listing|
            activity = Activity.find(listing.activity_id)
            activities << activity
        end
        self.events_attended.each do |signup|
            list = Listing.find(signup.listing_id)
            activity = Activity.find(list.activity_id)
            activities << activity
        end
        activities.uniq
    end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_logged_in, only: [:show, :update]
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_admin?, only: [:index, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if !@user
      redirect_to root_path
    end
    @num_total_attended = @profile.events_attended.length
    @num_organised = @profile.events_organised.length
    @organised = @profile.events_organised.sort_by(&:date)
    @activities = @profile.activities
    @listings = @profile.listings_attending.sort_by(&:date)
  end

  # GET /users/new
  def new
    if !logged_in?
      @user = User.new
    else
      redirect_to root_path
    end
  end

  # GET /users/1/edit
  def edit
    @profile = User.find(params[:id])
    if @user.admin || @profile.id == @user.id
      render "edit"
    else
      flash[:notice] = "You cannot edit someone else's profile."
      redirect_back(fallback_location: root_path)
    end
  end

  # def edit_password
  #   @profile = User.find(params[:id])
  #   render "edit_password"
  # end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render 'new'
      end
    end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @profile = User.find(params[:id])

      respond_to do |format|
        if @profile.update_attributes(user_params)
          format.html { redirect_to @profile, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @profile }
        else
          format.html { render :edit }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end
  end

  def update_password
    @profile = User.find(params[:id])
  end
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @profile = User.find(params[:id])
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @profile = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age, :bio, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="edit_user_container">
<h1>Create A New MixMatch Account</h1>
<div class="user_errors">
<% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors on your signup: </h2>
      <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
  </div>
    
<div class="update_user_form">
<%= form_for @profile, controller: 'users', action: 'update' do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :age %>
  <%= f.number_field :age, required: true %>

  <%= f.label 'Bio (Optional)' %>
  <%= f.text_area :bio, size: "30x10" %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.submit "update" %>
<% end %>
</div>

<%= link_to 'Back', user_path(@user.id) %>
</div>

app/views/users/edit_password.html.erb
<div class="update_user_form">
<%= form_for @profile, controller: 'users', action: 'update' do |f| %>
 <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <%= f.submit "update" %>
<% end %>
</div>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', user_path(@user.id) %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.age %></td>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Create A New MixMatch Account</h1><br>
<div class="new-user-page">
<div class="user_errors">
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>There were some errors on your signup: </h2>
        <% @user.errors.full_messages.each do |message| %>
          <%= message %> <br>
        <% end %>
    </div>
    <% end %>
  </div>
    
<div class="new_user_form">
<%= form_for @user, controller: 'users', action: 'create' do |f| %>
  <%= f.label 'User Name' %>
  <%= f.text_field :name, required: true %>

  <%= f.label :age %>
  <%= f.number_field :age, required: true %>

  <%= f.label 'Bio (Optional)' %>
  <%= f.text_area :bio, size: "30x10" %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %> <br> <br>

  <%= f.submit "Create Account" %>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p><br>
<div class="user-show">
  <div class="profile-information-container">
      <div class="profile-name">
      <H1><%= @profile.name %>'s profile</H1> <br>  
      <%= button_to "Edit Profile", edit_user_path(@profile), :method => :get%> 
      </div>
      <div class="profile-information">
      <div class="profile-details-card-container">
      <h3>Details</h3><br>
        <div class="profile-details-card">
          <p>
            <strong>Age:</strong>
            <%= @profile.age %>
          </p>

          <p>
            <strong>Email:</strong>
            <%= @profile.email %>
          </p>
          <p>
            <strong>Events attended:</strong>
            <%= @num_total_attended %>
          </p>
          <strong>Events organised:</strong>
            <%= @num_organised %>
          </p>
          <br>
          <strong>Bio:</strong><br>
          <%= @profile.bio %>
        </div>
        <br>
      </div>
  <div class="empty">
  </div>
  <div class="empty">
  </div>
  <div class="user-listings-container">
  <h3>Events Organised</h3><br>
    <div class="user-listings">
      <% if @organised.blank? %>
        <p>You haven't organised any events. Head over to <%= link_to 'the listings page', listings_path %> to create one</p><br><br>
      <% else %>
      <% @organised.each do |listing| %>
        <%= link_to listing_path(listing), action: 'go' do %>
          <div class="listing-card">
            <div class="listing-card-image">
              <% activity = Activity.find_by(id: listing.activity_id) %> 
              <img src=<%= activity.image_url %> alt=<%activity.name%>>
            </div>
            <br>
            <h3><%= listing.title %></h3>
            <p><%= listing.date.strftime("%a, %d %b") %></p>
            <br>
            <h4><%= activity.name %></h4>
            <br>
            <% ven = Venue.find_by(id: listing.venue_id) %>
            <p><%= ven.form_name %></p>
            <p>Spaces remaining: <%= listing.num_players - listing.players.length %></p>
          </div>
        <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
  </div>
  <div class="user-listings-container">
  <h3>Upcoming Events</h3><br>
    <div class="user-listings">
      <% @listings.each do |listing| %>
        <%= link_to listing_path(listing), action: 'go' do %>
          <div class="listing-card">
            <div class="listing-card-image">
              <% activity = Activity.find_by(id: listing.activity_id) %> 
              <img src=<%= activity.image_url %> alt=<%activity.name%>>
            </div>
            <br>
            <h3><%= listing.title %></h3>
            <p><%= listing.date.strftime("%a, %d %b") %></p>
            <br>
            <h4><%= activity.name %></h4>
            <br>
            <% ven = Venue.find_by(id: listing.venue_id) %>
            <p><%= ven.form_name %></p>
            <p>Spaces remaining: <%= listing.num_players - listing.players.length %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
      <%= button_to "Delete Profile", user_path(@profile), :method => :delete  %>
</div>