config/routes.rb
Rails.application.routes.draw do
  get 'admins/scaffold'
  resources :player_signups, only: [:delete]
  resources :listings
  resources :users
  resources :activities
  resources :venues
  resources :areas, only: [:index, :show] 
  namespace :admin do
    resources :users, only: [:delete]
    resources :venues, only: [:delete]
    resources :activities
    resources :areas, only: [:new, :create, :edit]
    resources :listings
  end

  post 'listings/:id', to: 'listings#join', as: 'join_listing'
  post 'player_signups/:id', to: 'listings#remove_player', as: 'delete_player_signup'


  # param: :slug
  get '/login' => 'sessions#new', as: 'login'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  root 'welcome#home'

  get '/users/:id/edit_password', to: 'users#edit_password', as: 'edit_user_password'
  patch '/users/:id', to: 'users#edit_password'

   # admin paths
  get '/admin', to: 'admins#index', as: 'admin'
  get '/admin/unauthorised_activities', to: 'admins#unauthorised_activities', as: 'unauthorised_activities'
  get '/activities/new', to: 'admins#new_activity'
  get '/admin/unauthorised_activities/:id/edit', to: 'admins#authorise', as: 'authorise_activity'
  
  patch '/admin/unauthorised_activities/:id', to: 'admins#update', as: 'update_activity'
  delete '/admin/unauthorised_activities/:id', to: 'admins#destroy_unauthorised_activity'

  # get '/activities/:slug', to: 'activities#show', as: 'activity'
  # get '/activities/:slug/edit', to: 'activities#edit', as: 'edit_activity'
  # patch 'activities/:slug', to: 'activities#update'

  # get '/users/:slug', to: 'users#show', as: 'user'
  # get '/users/:slug/edit', to: 'users#edit', as: 'edit_user'
  # patch '/users/:slug', to: 'users#update'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='menu-container'>
      <div class='menu'>
        <div class='nav'>
          <%= link_to 'Home', root_path %>
          <%= link_to 'Activities', activities_path %>
          <%= link_to 'Listings', listings_path %>
          <%= link_to 'Areas', areas_path %>
        </div>
          <% if logged_in? %>
          <div class="link-button">
            <div class="loggedin-as">
            Logged In as <%= @user.name %> <br>
            <p><%= link_to 'View Profile', user_path(@user.id) %></p>
            </div>
            <div class="logout-button">
            <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
            <input type=submit value='logout'>
            <% end %>
            </div>
          </div>
          <% else %>
        <div class="links">
          <div class='signup'><a href="/users/new">Sign Up</a></div>
        <% end %>
        </div>
      </div>
    </div>
    <div class="header-container">
      <div class="header">
        <div class='subscribe'></div>
          <div class='logo'><img src="https://i.imgur.com/A77x0iz.png" alt="MixMatch Logo"></div>
        <div class='social'></div>
      </div>
    </div>
    <div class="site-content">
      <%= yield %>
    </div>
    <div class="footer-container">
      <div class="footer">
        <div class="footer-logo">
          <img src="https://i.imgur.com/wOJk64P.png" alt="logo">
        </div>
        <div class="copyright">
          <p>Created with love by<br>MainMan Webworks. &copy; 2019. </p>
        </div>
        <div class="footer-items">
          <div class="nav-menu">
            <p><strong>Navigate</strong></p>
            <p><%= link_to 'Activities', activities_path %></p>
            <p><%= link_to 'Listings', listings_path %></p>
            <p><%= link_to 'Areas', areas_path %></p>
            <p><a href="mailto:support@mixmatch.com">Contact Us</a></p>
            <p><%= link_to 'About MixMatch', root_path %></p>
          </div>
          <div class="legal-bumf">
            <p><strong>Legal</strong></p>
            <p>Privacy Policy</p>
            <p>Terms and Conditions</p>
          </div>
          <div class="footer-account">
            <p><strong>User</strong></p>
            <% if @user.id %>
              <p><%= link_to 'View Profile', user_path(@user) %></p>
              <p><%= link_to 'Edit Profile', edit_user_path(@user) %></p> 
            <% else %>
              <p><%= link_to 'Log In', root_path %></p>
              <p><%= link_to 'Create Account', new_user_path %></p> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>